In [2]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
data=sns.load_dataset("titanic")

In [4]:
print(data.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

In [5]:
data.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [8]:
#not going to all the features only some features only !!!

In [9]:
features=["pclass","sex","fare","embarked","age"]
target=["survived"]

In [10]:
#missing values
from sklearn.impute import SimpleImputer
imp_mean=SimpleImputer(strategy="mean")
data[["age"]]=imp_mean.fit_transform(data[["age"]])
imp_freq=SimpleImputer(strategy="most_frequent")
data[["embarked"]]=imp_freq.fit_transform(data[["embarked"]])

In [12]:
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [13]:
data.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [21]:
#encode
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

data["sex"]=le.fit_transform(data["sex"])
data["embarked"]=le.fit_transform(data["embarked"])
data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,1,28,1,0,7.2500,2,Third,man,True,NaN,Southampton,no,False
1,1,1,0,52,1,0,71.2833,0,First,woman,False,C,Cherbourg,yes,False
2,1,3,0,34,0,0,7.9250,2,Third,woman,False,NaN,Southampton,yes,True
3,1,1,0,48,1,0,53.1000,2,First,woman,False,C,Southampton,yes,False
4,0,3,1,48,0,0,8.0500,2,Third,man,True,NaN,Southampton,no,True

In [22]:
x=data[features]
y=data[target]

In [24]:
x.head() , y.head()

(   pclass  sex     fare  embarked  age
 0       3    1   7.2500         2   28
 1       1    0  71.2833         0   52
 2       3    0   7.9250         2   34
 3       1    0  53.1000         2   48
 4       3    1   8.0500         2   48,
    survived
 0         0
 1         1
 2         1
 3         1
 4         0)

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [26]:
#model building

In [28]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [29]:
y_pred=model.predict(x_test)

In [30]:
from sklearn.metrics import accuracy_score

In [32]:
print(accuracy_score(y_test,y_pred))

0.7877094972067039

In [37]:
from sklearn.tree import plot_tree

In [34]:
plt.figure(figsize=(18,10))

In [39]:
plot_tree(model,feature_names=x.columns,class_names=["died","survived"],filled=True)
          plt.tight_layout()
          plt.show()

IndentationError: unexpected indent (3047772030.py, line 2)